org: phoenix031
app: api-project1
service: api-project1
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  api:
    handler: index.handler
    events:
      - httpApi: '*'
  auth-service-api:
    handler: auth-service/app.handler
    events : 
      - http:
          path: auth
          method: ANY
  user-service-api:
    handler: user-service/app.handler
    events :
      - http:
          path: user
          method: ANY